site_name: Ray-X
site_author: Ray-X
copyright: "Copyright &copy; 2019 - 2024 RayX"
site_url: https://ray-x.github.io
site_description: >-
  关于软件、Geek | Ray，Web & Mobile Lover，Software Engineer | 这里是 @Ray睿 类喵星人的个人博客。专注求索，创新
repo_url: https://github.com/ray-x.github.io
repo_name: ray-x
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
    - latest:
      - blog/posts/Python-AsynchronousIO.md
      - blog/posts/Python-Django-Django-Restful-Framework.md
theme:
  name: "material"
  custom_dir: overrides
  font: false
  icon:
    tag:
      css: simple/css3
      html: simple/html5
      js: simple/javascript
      python: simple/python
    logo: material/home
watch:
  - overrides
features:
  - content.action.edit
  - content.action.view
  - content.tooltips
  - navigation.tabs
  - navigation.tracking
  - navigation.sections
  - navigation.instant
  - navigation.indexes

plugins:
  - search
  - tags
  - blog:
      categories: true

hooks:
  - hooks/archive.py
markdown_extensions:
  - toc:
      permalink: true
      title: On this page
  - smarty
  - admonition
  - attr_list
  - md_in_html
  - meta
  - def_list
  - toc:
      permalink: true
  - footnotes
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
  - pymdownx.keys
  - pymdownx.tabbed
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ray-x
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/x_II_x
    - icon: fontawesome/brands/linkedin-in
      link: https://linkedin.com/in/ray-x
  tags:
    CSS: css
    HTML: html
    JavaScript: js
  blog:
    dir: blog
    list_length: 24
    extended_preview: true
    author: ray-x
    # author_image: https://user-images.githubusercontent.com/1681295/279851376-68b03a00-464e-4b6f-a348-03ce9e7fcf53.jpg
extra_css:
  - "stylesheets/extra.css"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
